
- platform: switch
  name: 1_livingroom_light
  entity_id: switch.1_livingroom_light
- platform: switch
  name: 1_bathroom_light_switch
  entity_id: switch.1_bathroom_light_switch
- platform: switch
  name: 1_washingroom_light_switch
  entity_id: switch.1_washingroom_light_switch
- platform: switch
  name: 1_hall_closet_light
  entity_id: switch.1_hall_closet_switch
- platform: switch
  name: 2_bathroom_light_switch
  entity_id: switch.2_bathroom_light_switch
- platform: switch
  name: 2_bedroom_hm_switch
  entity_id: switch.2_bedroom_hm_switch
- platform: switch
  name: garage_lights_switch
  entity_id: switch.garage_lights_switch

- platform: mqtt
  name: "garage spotlights"
  command_topic: "cmnd/garage_spotlights/power"
  state_topic: "stat/garage_spotlights/POWER"
  qos: 1
  payload_on: "ON"
  payload_off: "OFF"
  retain: true
- platform: mqtt
  name: "garage attic lights"
  command_topic: "cmnd/garage_attic_lights/power"
  state_topic: "stat/garage_attic_lights/POWER"
  qos: 1
  payload_on: "ON"
  payload_off: "OFF"
  retain: true
- platform: mqtt
  name: "1 kitchen sideboard"
  command_topic: "cmnd/1_kitchen_sideboard/power"
  state_topic: "stat/1_kitchen_sideboard/POWER"
  qos: 1
  payload_on: "ON"
  payload_off: "OFF"
  retain: true
